title: Prabhat Garg
logo: https://lh3.googleusercontent.com/0vVuN3yNFMhwYHr3Yq-jgSq8zetLoiPKsvTu9ttZgYCscrRdF0g4GX8naQFFanhxHUbIpDKFl-K4wBPbysXdkvg_E8jujkMkoUPVWwxHhZ7TfCFo4ZrBuDgMaPGU2nQUVwL3W-nLEa4=w2400
description: Still naive.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal