title: Prabhat Garg
logo: https://lh3.googleusercontent.com/TIaJM9z-v6r6nowx3_JNfvtVyBALzZ8vTbWLanLxF_gjPXWnSJ8-0H0ysV19OU84lKvSkg8F5mPHLQ4J-ZCBScPzdyC4xKWp-MWwMclIjs4OHG9GmEM39WSUKgNKe-FmDTtdvU0ve1M=w2400
description: Still naive.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal