title: Prabhat Garg
logo: https://lh3.googleusercontent.com/sj3MLVXzT2myDIpXAfMCq1XoYodYYCH5mEiUa-bB0Y67ardjG0QL2hUPlKcixN2HVvmzV2Nr7pWFo4o73h6OJaXC8OvfiyV-MVm_OJhc4XtTWqIB07OpFEHNf2NwRV0DkIERhCn8Uh-itY7G5q-tolZaNDcYIGF-jYyv-Khdn2XKIQ_wbJd5K-OB0A9GCI95U3QCDPhCPktYCZeGqSK_r5bYHTpPjrBUkvS730EHNFpcHnIxNXBxAolTlLc785O08ZR7lFDJ2EQ6rr35t-jsNM-MXqNJPQydWwbKvzlwlOVkbd1UC5nfU2nmX1DWXqc6us0E9r97t8va9FJHjU73aPGPKjW3MeCtZ90M-mHg-dc7c2wq1XkQMxBuuF4O4fX-koXbX1OD0F6v1Zd5dICnur8cp6yFN3igtO_gkknfCvKTVrAWUbEfOYv7VpnsZ5OgbVb2pGXQtBl79bl9j0qmXVTxWO3MbpaSk_GOcP9Tc5X-SDIFSEFqZOGUyAmwKXRRL9dPTvG0hjmwMnYbT_JAfPTSfNHVN3ANnoqp6xsfX60sO4TXsVecA-sRykDDOdjpWaOFG41HlwULpTL8rbkjUDgbtNEpIbdEvIWfovCrTZrllCDtZH7NCgwSCcEipTvJGzFNibbrNnGddPwTWNxdpDkaml9PaNCl_3jszyorGbtpayeh_cZD8dWqElXP7keRRU9vH-cOtx4mYZ5bNqPT23TPfQ=w832-h469-no
description: <p><small>Prabhat Garg is an engineer and a social entrepreneur. He works in the domains of technology, civic engagement, environment and sustainability.</small></p><a href="https://twitter.com/prabhatgarg">@prabhatgarg</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-sitemap
github:
  is_project_page: false